version: "3"

volumes:
  pg_data:

networks:
  default:
    name: tg-assistant-network

services:
  tg-assistant:
    image: ghcr.io/3ahat0p/tg-assistant:1.0.0
    container_name: tg-assistant
    environment:
      - IS_PROD_MODE=$IS_PROD_MODE
      - IS_COMPILED=$IS_COMPILED
      - LOG_LEVEL=$LOG_LEVEL
      - TG_BOT_TOKEN=$TG_BOT_TOKEN
      - SCHEDULE_RUN_DELAY=$SCHEDULE_RUN_DELAY
      - DEFAULT_TIMEZONE=$DEFAULT_TIMEZONE
      - DEFAULT_LOCALE=$DEFAULT_LOCALE
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_RUN_MIGRATIONS=$POSTGRES_RUN_MIGRATIONS
      - POSTGRES_ROLLBACK_MIGRATIONS=$POSTGRES_ROLLBACK_MIGRATIONS
      - SELF_HOST=$SELF_HOST
      - SELF_PORT=$SELF_PORT
      - SELF_PUBLIC_HOST=$SELF_PUBLIC_HOST
      - SELF_PUBLIC_PORT=$SELF_PUBLIC_PORT
    command: npm run prod:start
    restart: on-failure
  postgres:
    image: postgres:16
    container_name: tg-assistant-postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - TZ=Etc/UTC
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - 5432:5432