FROM node:21-alpine

WORKDIR /usr/src/app

ENV NODE_ENV=development
ENV IS_PROD_MODE=true
ENV IS_COMPILED=true

COPY ./package*.json ./

RUN npm ci

ENV NODE_ENV=production

COPY ./ ./

RUN npm run build

ENTRYPOINT [ "npm", "run", "prod:start" ]