version: "3"

volumes:
  pg_data:

networks:
  default:
    name: tg-assistant-network

services:
  postgres:
    image: postgres:16
    container_name: tg-assistant-postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - TZ=Etc/UTC
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - 5432:5432